
source 'https://rubygems.org'

gem "sinatra"
gem 'unicorn'
gem 'sequel'
gem 'content-security-policy'
gem 'escape_utils'
gem 'pg'
gem 'Jam_Func'

group :development do
  gem 'dot_why'
  gem 'mustache'
end

