function anonymous(locals, cb, __) {
    __ = __ || [];
    __.r = __.r || blade.Runtime;
    if (!__.func) __.func = {}, __.blocks = {}, __.chunk = {};
    __.locals = locals || {};
    __.base = "/home/da/DEV/apps/okdoki";
    __.rel = "Client/App/top_slash";
    __.filename = "/home/da/DEV/apps/okdoki/Client/App/top_slash/markup.blade";
    __.source = 'include "../../layout.blade"\n\nappend content\n\n  div.col#content\n    script#lifes(type="text/x-handlebars-template")\n      div.box#Watched\n        h3 Handlebars\n        div.content\n          P\n            | {{msg}}\n          span.display\n          span\n            | Text Value:\n          input(type="text", publish-to="span.display", value="Hello")\n          p\n            | Text:\n            span.get_tag\n              | ---\n          input.tag(type="text")\n          button(on-click="publish_tag")\n            | Add\n          ul(list="tags")\n            li\n              | name: {{name}}, num: {{num}}\n\n  div.sidebar#sidebar\n\n    h1.title\n      span.main ok\n      span.sub doki\n\n    div#header\n      p\n        span.about Multi-Life Chat & Publishing\n        br\n        span New features added each week.\n      p\n        strong ~ ~ ~\n\n    call applet("New_Session")\n    call applet("New_Customer")\n\n    div(id=\'footer\')\n      p\n        | (c) 2012-2013 OKdoki.com. Some rights reserved.\n      p\n        | All other copyrights belong to their respective owners.\n      p\n        | Cover Photo:\n        a(href="http://www.dreamstime.com/bikes-in-a-row-free-stock-photos-imagefree84388")\n          | Bikes in Montreal\n      p\n        | Logo font:\n        a(href="http://lenkavomelova.com/")\n          | Lenka Stabilo\n\n      p\n        | Life & Website Header font:\n        a(href="http://openfontlibrary.org/en/font/circus")\n          | Circus\n\n      p\n        | Wood Pattern:\n        a(href="http://subtlepatterns.com/wood-pattern/")\n          | Alexey Usoltsev\n\n      p\n        | Ravenna Pattern:\n        a(href="http://subtlepatterns.com/ravenna/")\n          | Sentel\n\n      P\n        | Escheresque Pattern:\n        a(href="http://subtlepatterns.com/?s=Escheresque&submit=Search")\n          | Ste Patten & Jan Meeus\n\n      P\n        | Profile Page Palette:\n        a(href="http://www.colourlovers.com/lover/dvdcpd")\n          | dvdcpd\n        a(href="http://www.colourlovers.com/palette/154398/bedouin")\n          | shari_foru\n\nappend content\n  div.col#Why\n    h3 Create Multiple Lifes\n    div.content\n      | One account can manage different screen names\n      | at the same time. Keep things separate from among\n      | co-workers, friends, and family.\n\n    h3 A New Feature Each Week\n\n    div.content\n      strong This Week:\n      span\n        |  Chat Rooms\n      br\n      span\n        | Use a\n        | different screen name (aka life)\n        | in each chat room.\n\n    div.content\n      strong Next Week:\n      span\n        |  RSS/JSON in Chat\n      br\n      span\n        | Have RSS items\n        | stream into your chat window.\n\n\n\n\n\n\n\n\n';
    try {
        with (__.locals) {
            __.line = 1, __.col = 1;
            __.r.include("../../layout.blade", __);
            __.line = 3, __.col = 1;
            __.r.blockMod("a", "content", __, function(__) {
                __.line = 5, __.col = 3;
                __.push("<div" + ' id="content"' + ' class="col"' + ">");
                __.line = 6, __.col = 5;
                __.push("<script" + ' type="text/x-handlebars-template"' + ' id="lifes"' + ">");
                __.line = 7, __.col = 7;
                __.push("<div" + ' id="Watched"' + ' class="box"' + ">");
                __.line = 8, __.col = 9;
                __.push("<h3" + ">" + "Handlebars" + "</h3>");
                __.line = 9, __.col = 9;
                __.push("<div" + ' class="content"' + ">");
                __.line = 10, __.col = 11;
                __.push("<P" + ">");
                __.line = 11, __.col = 13;
                __.push("{{msg}}" + "</P>");
                __.line = 12, __.col = 11;
                __.push("<span" + ' class="display"' + ">" + "</span>");
                __.line = 13, __.col = 11;
                __.push("<span" + ">");
                __.line = 14, __.col = 13;
                __.push("Text Value:" + "</span>");
                __.line = 15, __.col = 11;
                __.push("<input" + ' type="text"' + ' publish-to="span.display"' + ' value="Hello"' + "/>");
                __.line = 16, __.col = 11;
                __.push("<p" + ">");
                __.line = 17, __.col = 13;
                __.push("Text:");
                __.line = 18, __.col = 13;
                __.push("<span" + ' class="get_tag"' + ">");
                __.line = 19, __.col = 15;
                __.push("---" + "</span>" + "</p>");
                __.line = 20, __.col = 11;
                __.push("<input" + ' type="text"' + ' class="tag"' + "/>");
                __.line = 21, __.col = 11;
                __.push("<button" + ' on-click="publish_tag"' + ">");
                __.line = 22, __.col = 13;
                __.push("Add" + "</button>");
                __.line = 23, __.col = 11;
                __.push("<ul" + ' list="tags"' + ">");
                __.line = 24, __.col = 13;
                __.push("<li" + ">");
                __.line = 25, __.col = 15;
                __.push("name: {{name}}, num: {{num}}" + "</li>" + "</ul>" + "</div>" + "</div>" + "</script>" + "</div>");
                __.line = 27, __.col = 3;
                __.push("<div" + ' id="sidebar"' + ' class="sidebar"' + ">");
                __.line = 29, __.col = 5;
                __.push("<h1" + ' class="title"' + ">");
                __.line = 30, __.col = 7;
                __.push("<span" + ' class="main"' + ">" + "ok" + "</span>");
                __.line = 31, __.col = 7;
                __.push("<span" + ' class="sub"' + ">" + "doki" + "</span>" + "</h1>");
                __.line = 33, __.col = 5;
                __.push("<div" + ' id="header"' + ">");
                __.line = 34, __.col = 7;
                __.push("<p" + ">");
                __.line = 35, __.col = 9;
                __.push("<span" + ' class="about"' + ">" + "Multi-Life Chat &amp; Publishing" + "</span>");
                __.line = 36, __.col = 9;
                __.push("<br" + "/>");
                __.line = 37, __.col = 9;
                __.push("<span" + ">" + "New features added each week." + "</span>" + "</p>");
                __.line = 38, __.col = 7;
                __.push("<p" + ">");
                __.line = 39, __.col = 9;
                __.push("<strong" + ">" + "~ ~ ~" + "</strong>" + "</p>" + "</div>");
                __.line = 41, __.col = 5;
                __.r.call("applet", {}, __, "New_Session");
                __.line = 42, __.col = 5;
                __.r.call("applet", {}, __, "New_Customer");
                __.line = 44, __.col = 5;
                __.push("<div" + ' id="footer"' + ">");
                __.line = 45, __.col = 7;
                __.push("<p" + ">");
                __.line = 46, __.col = 9;
                __.push("(c) 2012-2013 OKdoki.com. Some rights reserved." + "</p>");
                __.line = 47, __.col = 7;
                __.push("<p" + ">");
                __.line = 48, __.col = 9;
                __.push("All other copyrights belong to their respective owners." + "</p>");
                __.line = 49, __.col = 7;
                __.push("<p" + ">");
                __.line = 50, __.col = 9;
                __.push("Cover Photo:");
                __.line = 51, __.col = 9;
                __.push("<a" + ' href="http://www.dreamstime.com/bikes-in-a-row-free-stock-photos-imagefree84388"' + ">");
                __.line = 52, __.col = 11;
                __.push("Bikes in Montreal" + "</a>" + "</p>");
                __.line = 53, __.col = 7;
                __.push("<p" + ">");
                __.line = 54, __.col = 9;
                __.push("Logo font:");
                __.line = 55, __.col = 9;
                __.push("<a" + ' href="http://lenkavomelova.com/"' + ">");
                __.line = 56, __.col = 11;
                __.push("Lenka Stabilo" + "</a>" + "</p>");
                __.line = 58, __.col = 7;
                __.push("<p" + ">");
                __.line = 59, __.col = 9;
                __.push("Life &amp; Website Header font:");
                __.line = 60, __.col = 9;
                __.push("<a" + ' href="http://openfontlibrary.org/en/font/circus"' + ">");
                __.line = 61, __.col = 11;
                __.push("Circus" + "</a>" + "</p>");
                __.line = 63, __.col = 7;
                __.push("<p" + ">");
                __.line = 64, __.col = 9;
                __.push("Wood Pattern:");
                __.line = 65, __.col = 9;
                __.push("<a" + ' href="http://subtlepatterns.com/wood-pattern/"' + ">");
                __.line = 66, __.col = 11;
                __.push("Alexey Usoltsev" + "</a>" + "</p>");
                __.line = 68, __.col = 7;
                __.push("<p" + ">");
                __.line = 69, __.col = 9;
                __.push("Ravenna Pattern:");
                __.line = 70, __.col = 9;
                __.push("<a" + ' href="http://subtlepatterns.com/ravenna/"' + ">");
                __.line = 71, __.col = 11;
                __.push("Sentel" + "</a>" + "</p>");
                __.line = 73, __.col = 7;
                __.push("<P" + ">");
                __.line = 74, __.col = 9;
                __.push("Escheresque Pattern:");
                __.line = 75, __.col = 9;
                __.push("<a" + ' href="http://subtlepatterns.com/?s=Escheresque&amp;submit=Search"' + ">");
                __.line = 76, __.col = 11;
                __.push("Ste Patten &amp; Jan Meeus" + "</a>" + "</P>");
                __.line = 78, __.col = 7;
                __.push("<P" + ">");
                __.line = 79, __.col = 9;
                __.push("Profile Page Palette:");
                __.line = 80, __.col = 9;
                __.push("<a" + ' href="http://www.colourlovers.com/lover/dvdcpd"' + ">");
                __.line = 81, __.col = 11;
                __.push("dvdcpd" + "</a>");
                __.line = 82, __.col = 9;
                __.push("<a" + ' href="http://www.colourlovers.com/palette/154398/bedouin"' + ">");
                __.line = 83, __.col = 11;
                __.push("shari_foru" + "</a>" + "</P>" + "</div>" + "</div>");
            });
            __.line = 85, __.col = 1;
            __.r.blockMod("a", "content", __, function(__) {
                __.line = 86, __.col = 3;
                __.push("<div" + ' id="Why"' + ' class="col"' + ">");
                __.line = 87, __.col = 5;
                __.push("<h3" + ">" + "Create Multiple Lifes" + "</h3>");
                __.line = 88, __.col = 5;
                __.push("<div" + ' class="content"' + ">");
                __.line = 89, __.col = 7;
                __.push("One account can manage different screen names");
                __.line = 90, __.col = 7;
                __.push("\nat the same time. Keep things separate from among");
                __.line = 91, __.col = 7;
                __.push("\nco-workers, friends, and family." + "</div>");
                __.line = 93, __.col = 5;
                __.push("<h3" + ">" + "A New Feature Each Week" + "</h3>");
                __.line = 95, __.col = 5;
                __.push("<div" + ' class="content"' + ">");
                __.line = 96, __.col = 7;
                __.push("<strong" + ">" + "This Week:" + "</strong>");
                __.line = 97, __.col = 7;
                __.push("<span" + ">");
                __.line = 98, __.col = 9;
                __.push(" Chat Rooms" + "</span>");
                __.line = 99, __.col = 7;
                __.push("<br" + "/>");
                __.line = 100, __.col = 7;
                __.push("<span" + ">");
                __.line = 101, __.col = 9;
                __.push("Use a");
                __.line = 102, __.col = 9;
                __.push("\ndifferent screen name (aka life)");
                __.line = 103, __.col = 9;
                __.push("\nin each chat room." + "</span>" + "</div>");
                __.line = 105, __.col = 5;
                __.push("<div" + ' class="content"' + ">");
                __.line = 106, __.col = 7;
                __.push("<strong" + ">" + "Next Week:" + "</strong>");
                __.line = 107, __.col = 7;
                __.push("<span" + ">");
                __.line = 108, __.col = 9;
                __.push(" RSS/JSON in Chat" + "</span>");
                __.line = 109, __.col = 7;
                __.push("<br" + "/>");
                __.line = 110, __.col = 7;
                __.push("<span" + ">");
                __.line = 111, __.col = 9;
                __.push("Have RSS items");
                __.line = 112, __.col = 9;
                __.push("\nstream into your chat window." + "</span>" + "</div>" + "</div>");
            });
        }
    } catch (e) {
        return cb(__.r.rethrow(e, __));
    }
    if (!__.inc) __.r.done(__);
    cb(null, __.join(""), __);
}
var runtime = require('./runtime');
var blade = runtime.blade;
exports.render = anonymous;
